### ISSUE TITLE
Bug in mapping pipeline

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#130]
```
Traceback (most recent call last):
  File "/usr/local/bin/sssom", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sssom/cli.py", line 208, in parse
    parse_file(
  File "/usr/local/lib/python3.10/dist-packages/sssom/io.py", line 112, in parse_file
    doc.clean_prefix_map()
  File "/usr/local/lib/python3.10/dist-packages/sssom/util.py", line 169, in clean_prefix_map
    raise ValueError(
ValueError: ['MeSH'] are used in the SSSOM mapping set but it does not exist in the prefix map
make[1]: *** [mondo-ingest.Makefile:170: ../mappings/ordo.sssom.tsv] Error 1
make[1]: Leaving directory '/work/src/ontology'
make: *** [mondo-ingest.Makefile:278: build-mondo-ingest] Error 2
Command exited with non-zero status 2
```

**Comment by hrshdhgd** [comment]
It's not a bug, it's a feature! 😆 

https://github.com/mapping-commons/sssom-py/pull/329#issue-1497518590

**Comment by matentzn** [comment]
Yeah.. a feature for sssom-py, but a bug for the ingest pipeline :P It would be great if you could prioritise this for the Mondo hackathon next week!

**Comment by hrshdhgd** [comment]
It seems like `component-orzo.json` has both `MESH` and  `MeSH` as the prefix, which one is correct?
```
{
      "id" : "http://www.orpha.net/ORDO/Orphanet_100999",
      "lbl" : "Autosomal dominant spastic paraplegia type 19",
      "type" : "CLASS",
      "meta" : {
        "definition" : {
          "val" : "A pure form of hereditary spastic paraplegia characterized by a slowly progressive and relatively benign spastic paraplegia presenting in adulthood with spastic gait, lower limb hyperreflexia, extensor plantar responses, bladder dysfunction (urinary urgency and/or incontinence), and mild sensory and motor peripheral neuropathy."
        },
        "subsets" : [ "http://purl.obolibrary.org/obo/mondo#ordo_disorder", "http://purl.obolibrary.org/obo/mondo#ordo_group_of_disorders" ],
        "synonyms" : [ {
          "pred" : "hasExactSynonym",
          "val" : "SPG19"
        } ],
        "xrefs" : [ {
          "val" : "ICD-10:G11.4"
        }, {
          "val" : "ICD10:G11.4"
        }, {
          "val" : "MESH:C536856"
        }, {
          "val" : "MeSH:C536856"
        }, {
          "val" : "OMIM:607152"
        }, {
          "val" : "UMLS:C1846685"
        } ]
      }
    }
```

**Comment by matentzn** [comment]
Shouldn't the pipeline simply ignore the values for which there is no prefix rather than fail hard? Or some other setting by which we can say, "clean out unknown prefixes"?

**Comment by hrshdhgd** [comment]
Fail hard is what Chris wanted: https://github.com/mapping-commons/sssom-py/issues/328#issue-1497517479

**Comment by matentzn** [comment]
Hm. Ok.. Can you fix it then by adding the prefixes?

**Comment by hrshdhgd** [comment]
So 2 prefixes for MeSH?
