### ISSUE TITLE
Bug `No such file or directory` in migrate.py

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#291]
Probably my fault as I merged your PR too quick, but best leave PRs in draft mode when they are not ready to merge 🙏 

```
/usr/local/lib/python3.10/dist-packages/rdflib_jsonld/__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/pronto/ontology.py:283: NotImplementedWarning: cannot process plain `owl:AnnotationProperty`
  cls(self).parse_from(_handle)  # type: ignore
Traceback (most recent call last):
  File "/work/src/ontology/../scripts/migrate.py", line 226, in <module>
    cli()
  File "/work/src/ontology/../scripts/migrate.py", line 222, in cli
    return slurp_docs() if docs else slurp(**d)
  File "/work/src/ontology/../scripts/migrate.py", line 91, in slurp
    owned_terms: List[Term] = _get_all_owned_terms(
  File "/work/src/scripts/utils.py", line 279, in _get_all_owned_terms
    direct_parents_df: pd.DataFrame = jinja_sparql(
  File "/work/src/scripts/utils.py", line 400, in jinja_sparql
    os.remove(command_str)
FileNotFoundError: [Errno 2] No such file or directory: 'robot query --input components/omim.owl --query /work/src/ontology/tmp/robot/omim-owl__get-terms-direct-parents/query.sparql /work/src/ontology/tmp/robot/omim-owl__get-terms-direct-parents/results.csv'
make[2]: *** [mondo-ingest.Makefile:435: slurp/omim.tsv] Error 1
make[2]: Leaving directory '/work/src/ontology'
make[1]: *** [mondo-ingest.Makefile:448: slurp-omim] Error 2
make[1]: Leaving directory '/work/src/ontology'
make: *** [mondo-ingest.Makefile:302: build-mondo-ingest] Error 2
Command exited with non-zero status 2
```

**Comment by joeflack4** [comment]
No, it's not your fault. I un-drafted the PR because I thought it was ready. I think I know what's causing this and I thought I addressed this, my apologies. Will fix.
