### ISSUE TITLE
Bug empty SSSOM file

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#294]
This never happened before: weird it is happening now:

```
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/sssom", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sssom/cli.py", line 609, in sort
    msdf = parse_sssom_table(input)
  File "/usr/local/lib/python3.10/dist-packages/sssom/parsers.py", line 142, in parse_sssom_table
    df = read_pandas(file_path)
  File "/usr/local/lib/python3.10/dist-packages/sssom/util.py", line 950, in read_pandas
    df = read_csv(file, comment="#", sep=sep).fillna("")
  File "/usr/local/lib/python3.10/dist-packages/sssom/util.py", line 919, in read_csv
    return pd.read_csv(StringIO(lines), sep=sep, low_memory=False)
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 554, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
make[1]: *** [mondo-ingest.Makefile:164: ../mappings/icd10cm.sssom.tsv] Error 1
make[1]: Leaving directory '/work/src/ontology'
make: *** [mondo-ingest.Makefile:303: build-mondo-ingest] Error 2
```

**Comment by matentzn** [comment]
```
root@8cfaa26cdfd6:/work/src/ontology# pip list | grep sss
sssom                         0.3.28
sssom-schema                  0.11.0
```

**Comment by hrshdhgd** [comment]
Update to `sssom` 0.3.30. This issue should be resolved

**Comment by matentzn** [comment]
Confirmed, fixed with the latest sssom version.
