### ISSUE TITLE
Missing module rustsim

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#305]
This goal: `reports/mirror_signature-ncit.tsv` now fails with the latest OAK release.

```
python3 ../scripts/mirror_signature_via_oak.py --db-path components/ncit.db --onto-config-path metadata/ncit.yml --outpath reports/mirror_signature-ncit.tsv
/usr/local/lib/python3.10/dist-packages/rdflib_jsonld/__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  warnings.warn(
Traceback (most recent call last):
  File "/work/src/ontology/../scripts/mirror_signature_via_oak.py", line 13, in <module>
    from oaklib import get_implementation_from_shorthand
  File "/usr/local/lib/python3.10/dist-packages/oaklib/__init__.py", line 9, in <module>
    from oaklib.selector import get_adapter, get_implementation_from_shorthand  # noqa:F401
  File "/usr/local/lib/python3.10/dist-packages/oaklib/selector.py", line 15, in <module>
    from oaklib.implementations.funowl.funowl_implementation import FunOwlImplementation
  File "/usr/local/lib/python3.10/dist-packages/oaklib/implementations/__init__.py", line 39, in <module>
    from oaklib.implementations.rustsim.rustsim_implementation import RustSimImplementation
  File "/usr/local/lib/python3.10/dist-packages/oaklib/implementations/rustsim/rustsim_implementation.py", line 10, in <module>
    from rustsim import get_intersection, jaccard_similarity, mrca_and_score
ModuleNotFoundError: No module named 'rustsim'
make[3]: *** [mondo-ingest.Makefile:356: reports/mirror_signature-ncit.tsv] Error 1
make[3]: Leaving directory '/work/src/ontology'
make[2]: *** [mondo-ingest.Makefile:238: exclusions-ncit] Error 2
make[2]: Leaving directory '/work/src/ontology'
make[1]: *** [mondo-ingest.Makefile:243: exclusions-all] Error 2
make[1]: Leaving directory '/work/src/ontology'
make: *** [mondo-ingest.Makefile:301: build-mondo-ingest] Error 2
Command exited with non-zero status 2
### DEBUG STATS ###
Elapsed time: 59:34.38
Peak memory: 15946696 kb
```

For the record:

```
sh run.sh pip list | grep oak
oaklib                        0.5.5
```

@hrshdhgd I don't know if you have an immediate idea, else I will send @joeflack4 on a hunt.

**Comment by hrshdhgd** [comment]
I did the following:
 - `docker pull obolibrary/odkfull:dev`
 -  `ODK_TAG=dev sh run.sh make reports/mirror_signature-ncit.tsv` 

and it seems to work.

**Comment by joeflack4** [comment]
I agree this looks like something that needs an OAK fix, like a `pyproject.toml` addition. I can make a PR w/ that or an issue, though I'm not familiar with `rustsim` so will defer to Harshad for now.

**Comment by matentzn** [comment]
@joeflack4 Harshad is on leave until further notice and this is a major blocker now.. Can you try to take care of it? I would reach out to oak people first, because the solution is _not_ to add the rustsim dependency, but to remove the whatever code still has it..

**Comment by matentzn** [comment]
(rustsim dependency was supposedly renamed)

**Comment by joeflack4** [comment]
Thanks for sharing the Slack thread with me. So I suppose one of us just needs to upgrade OAK in the python-requirements file. Then we can upgrade it locally and this problem should go away.

**Comment by matentzn** [comment]
Works now!
