### ISSUE TITLE
Bug KeyError: 'mondo_id' in migrate.py

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#309]
After updateing to latest OAK, I know get this:

```
robot --catalog catalog-v001.xml query -i tmp/mondo.owl --query ../sparql/classes.sparql reports/mirror_signature-mondo.tsv
(head -n 1 reports/mirror_signature-mondo.tsv && tail -n +2 reports/mirror_signature-mondo.tsv | sort) > reports/mirror_signature-mondo.tsv-temp
mv reports/mirror_signature-mondo.tsv-temp reports/mirror_signature-mondo.tsv
mkdir -p slurp/
python3 ../scripts/migrate.py \
--ontology-path components/ordo.owl \
--mondo-mappings-path tmp/mondo.sssom.tsv \
--onto-config-path metadata/ordo.yml \
--onto-exclusions-path reports/ordo_term_exclusions.txt \
--min-id 850056 \
--max-id 999999 \
--mondo-terms-path reports/mirror_signature-mondo.tsv \
--slurp-dir-path slurp/ \
--outpath slurp/ordo.tsv
/usr/local/lib/python3.10/dist-packages/rdflib_jsonld/__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/pronto/ontology.py:283: NotImplementedWarning: cannot process plain `owl:AnnotationProperty`
  cls(self).parse_from(_handle)  # type: ignore
Traceback (most recent call last):
  File "/work/src/ontology/../scripts/migrate.py", line 226, in <module>
    cli()
  File "/work/src/ontology/../scripts/migrate.py", line 222, in cli
    return slurp_docs() if docs else slurp(**d)
  File "/work/src/ontology/../scripts/migrate.py", line 131, in slurp
    result = result.sort_values(
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 6894, in sort_values
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 6894, in <listcomp>
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'mondo_id'
make[2]: *** [mondo-ingest.Makefile:439: slurp/ordo.tsv] Error 1
make[2]: Leaving directory '/work/src/ontology'
make[1]: *** [mondo-ingest.Makefile:452: slurp-ordo] Error 2
make[1]: Leaving directory '/work/src/ontology'
make: *** [mondo-ingest.Makefile:302: build-mondo-ingest] Error 2
Command exited with non-zero status 2
```

**Comment by joeflack4** [comment]
Hmm, that's unfortunate. Maybe this is a good time for me to try and find a good unit test for this. I will solve.

**Comment by joeflack4** [comment]
Simple bugfix. Sorry, I try to remember to do this check where I see if the dataframe is empty before trying to sort it, but I forgot to do so here.
