### ISSUE TITLE
ERROR: `max() arg is an empty sequence`

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#314]
```
python3 ../scripts/migrate.py \
--ontology-path components/ncit.owl \
--mondo-mappings-path tmp/mondo.sssom.tsv \
--onto-config-path metadata/ncit.yml \
--onto-exclusions-path reports/ncit_term_exclusions.txt \
--min-id 850056 \
--max-id 999999 \
--mondo-terms-path reports/mirror_signature-mondo.tsv \
--slurp-dir-path slurp/ \
--outpath slurp/ncit.tsv
/usr/local/lib/python3.10/dist-packages/rdflib_jsonld/__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/pronto/ontology.py:283: NotImplementedWarning: cannot process plain `owl:AnnotationProperty`
  cls(self).parse_from(_handle)  # type: ignore
Traceback (most recent call last):
  File "/work/src/ontology/../scripts/migrate.py", line 227, in <module>
    cli()
  File "/work/src/ontology/../scripts/migrate.py", line 223, in cli
    return slurp_docs() if docs else slurp(**d)
  File "/work/src/ontology/../scripts/migrate.py", line 77, in slurp
    next_mondo_id = max(next_mondo_id, max(slurp_ids) + 1)
ValueError: max() arg is an empty sequence
make[2]: *** [mondo-ingest.Makefile:439: slurp/ncit.tsv] Error 1
```

**Comment by matentzn** [comment]
I think we need some kind of integration testing for our pipeline.

**Comment by joeflack4** [comment]
True, I think we do. I think in this case an integration test would pass, because we'd be setting the inputs in stone, and it wouldn't catch this edge case. I think what's causing it is another similar issue where there are no slurp candidates. So for that, an unit test would be just as good / easier I think.

I'll get to fixing this edge case, sorry.

**Comment by joeflack4** [comment]
FYI, this could possibly be problematic / impossible for me to troubleshoot directly because I run out of memory when creating NCIT artefacts locally.
