### ISSUE TITLE
Bug: Mondo ingest (lexmatch pipeline)

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#343]
@hrshdhgd while you are at it, we need a way to prevent this from happening in the future.. Some kind of min test pipeline that must be run locally to ensure that the pipeline still works after refactorings..

```
python ../scripts/match-mondo-sources-all-lexical.py run tmp/merged.db \
        -c metadata/mondo.sssom.config.yml \
        -r config/mondo-match-rules.yaml \
        --rejects ../mappings/rejected-mappings.tsv \
        -o ../mappings/mondo-sources-all-lexical.sssom.tsv
/usr/local/lib/python3.10/dist-packages/rdflib_jsonld/__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  warnings.warn(
WARNING:root:No License provided, using https://w3id.org/sssom/license/unspecified
WARNING:root:Cannot automatically determine table format, trying tsv.
Traceback (most recent call last):
  File "/work/src/ontology/../scripts/match-mondo-sources-all-lexical.py", line 174, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/work/src/ontology/../scripts/match-mondo-sources-all-lexical.py", line 137, in run
    msdf.remove_mappings(mapping_msdf)
  File "/usr/local/lib/python3.10/dist-packages/sssom/util.py", line 199, in remove_mappings
    pd.merge(
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/reshape/merge.py", line 110, in merge
    op = _MergeOperation(
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/reshape/merge.py", line 703, in __init__
    ) = self._get_merge_keys()
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/reshape/merge.py", line 1162, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'predicate_modifier'
make[1]: *** [mondo-ingest.Makefile:435: ../mappings/mondo-sources-all-lexical.sssom.tsv] Error 1
rm imports/ro_terms_combined.txt
make[1]: Leaving directory '/work/src/ontology'
make: *** [mondo-ingest.Makefile:326: build-mondo-ingest] Error 2
Command exited with non-zero status 2
```

**Comment by hrshdhgd** [comment]
Yes I saw this error and fixed it too. The google sheet had empty `predicate_modifier`s for the last 2 rows and I filled them with `semapv:UnspecifiedMatching`. You need to re`make` `rejected-mappings.tsv`

**Comment by hrshdhgd** [comment]
ok, [`mondo.sssom.tsv`](https://raw.githubusercontent.com/monarch-initiative/mondo/master/src/ontology/mappings/mondo.sssom.tsv) in MONDO does not have the column name mentioned in the error. Hence the error. 

Do we need to make changes in `sssom-py` to make sure which SSSOM columns are the bare minimum needed to be present even if the column is empty?

For now I have a simple fix in place (#344).

**Comment by matentzn** [comment]
This column is _not_ required! So sssom-py cannot fail if the column ins not present! Did sssom py fail or your code?

**Comment by hrshdhgd** [comment]
`sssom-py` failed. PR: https://github.com/mapping-commons/sssom-py/pull/389

**Comment by matentzn** [comment]
#389 alone did not solve this:

```
Traceback (most recent call last):
  File "/work/src/ontology/../scripts/match-mondo-sources-all-lexical.py", line 176, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/work/src/ontology/../scripts/match-mondo-sources-all-lexical.py", line 139, in run
    msdf.remove_mappings(mapping_msdf)
  File "/usr/local/lib/python3.10/dist-packages/sssom/util.py", line 199, in remove_mappings
    pd.merge(
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/reshape/merge.py", line 110, in merge
    op = _MergeOperation(
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/reshape/merge.py", line 703, in __init__
    ) = self._get_merge_keys()
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/reshape/merge.py", line 1162, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'predicate_modifier'
make[1]: *** [mondo-ingest.Makefile:435: ../mappings/mondo-sources-all-lexical.sssom.tsv] Error 1
rm imports/ro_terms_combined.txt
make[1]: Leaving directory '/work/src/ontology'
make: *** [mondo-ingest.Makefile:326: build-mondo-ingest] Error 2
Command exited with non-zero status 2

```

**Comment by matentzn** [comment]
This has been fixed but we forgot to link it to a PR
