### ISSUE TITLE
OAK (and other Python packages) outdated in Docker even after `install --upgrade` 

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#56]
## Overview
I was tinkering with OAK, trying to find the best implementation to use, and I settled on `ProntoImplementation`. In my Python IDE debugging environment, I had no problem using `ProntoImplementation`. However, when I ran the Python script via the `makefile` (`sh run.sh make <TARGET>`), I got unexpected OAK errors.

## First error: solved
`AttributeError: 'ProntoImplementation' object has no attribute 'entities'`:
```
python ../scripts/migrate.py \
--ontology-path components/ncit.owl \
--sssom-map-path tmp/mondo.sssom.tsv \
--min-id 123000 \
--mondo-terms-path reports/mirror_signature-mondo.tsv \
--outpath slurp/ncit.tsv
/usr/local/lib/python3.10/dist-packages/rdflib_jsonld/__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/pronto/parsers/rdfxml.py:286: SyntaxWarning: <Element '{http://protege.stanford.edu/plugins/owl/protege#}defaultLanguage' at 0x7f33d300ba10> contains text but no `xsd:datatype`
  meta.annotations.add(self._extract_literal_pv(child))
/usr/local/lib/python3.10/dist-packages/pronto/parsers/rdfxml.py:286: SyntaxWarning: <Element '{http://www.w3.org/2002/07/owl#}versionInfo' at 0x7f33d300bd80> contains text but no `xsd:datatype`
  meta.annotations.add(self._extract_literal_pv(child))
/usr/local/lib/python3.10/dist-packages/pronto/ontology.py:283: NotImplementedWarning: cannot process plain `owl:AnnotationProperty`
  cls(self).parse_from(_handle)  # type: ignore
/usr/local/lib/python3.10/dist-packages/pronto/parsers/rdfxml.py:117: SyntaxWarning: unknown element in `owl:Class`: {http://www.w3.org/2002/07/owl#}equivalentClass
  self._extract_term(class_, curies)
Traceback (most recent call last):
  File "/work/src/ontology/../scripts/migrate.py", line 141, in <module>
    cli()
  File "/work/src/ontology/../scripts/migrate.py", line 137, in cli
    run(**d)
  File "/work/src/ontology/../scripts/migrate.py", line 76, in run
    source_onto_terms: List[str] = _get_all_term_curies(ontology, is_omim='omim' in os.path.basename(ontology_path))
  File "/work/src/ontology/../scripts/migrate.py", line 50, in _get_all_term_curies
    terms = [x for x in ontology.entities()]
AttributeError: 'ProntoImplementation' object has no attribute 'entities'
```

## Second error: Unsolved
`ValueError: invalid identifier: https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/ALDH1A1`:
```
python ../scripts/[migrate.py](http://migrate.py/) \
--ontology-path components/omim.owl \
--sssom-map-path tmp/mondo.sssom.tsv \
--min-id 123000 \
--mondo-terms-path reports/mirror_signature-mondo.tsv \
--outpath slurp/omim.tsv
/usr/local/lib/python3.10/dist-packages/rdflib_jsonld/__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/pronto/parsers/[rdfxml.py](http://rdfxml.py/):286: SyntaxWarning: <Element '{http://www.w3.org/2002/07/owl#}versionInfo' at 0x7f2cfee17510> contains text but no `xsd:datatype`
  meta.annotations.add(self._extract_literal_pv(child))
/usr/local/lib/python3.10/dist-packages/pronto/[ontology.py](http://ontology.py/):283: NotImplementedWarning: cannot process plain `owl:AnnotationProperty`
  cls(self).parse_from(_handle)  # type: ignore
Traceback (most recent call last):
  File "/work/src/ontology/../scripts/[migrate.py](http://migrate.py/)", line 142, in <module>
    cli()
  File "/work/src/ontology/../scripts/[migrate.py](http://migrate.py/)", line 138, in cli
    run(**d)
  File "/work/src/ontology/../scripts/[migrate.py](http://migrate.py/)", line 71, in run
    ontology = ProntoImplementation(OntologyResource(slug=ontology_path, local=True))
  File "<string>", line 6, in __init__
  File "/usr/local/lib/python3.10/dist-packages/oaklib/implementations/pronto/[pronto_implementation.py](http://pronto_implementation.py/)", line 74, in __post_init__
    ontology = Ontology(str(resource.local_path))
  File "/usr/local/lib/python3.10/dist-packages/pronto/[ontology.py](http://ontology.py/)", line 283, in __init__
    cls(self).parse_from(_handle)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/pronto/parsers/[rdfxml.py](http://rdfxml.py/)", line 117, in parse_from
    self._extract_term(class_, curies)
  File "/usr/local/lib/python3.10/dist-packages/pronto/parsers/[rdfxml.py](http://rdfxml.py/)", line 444, in _extract_term
    termdata.annotations.add(self._extract_resource_pv(child))
  File "/usr/local/lib/python3.10/dist-packages/pronto/parsers/[rdfxml.py](http://rdfxml.py/)", line 223, in _extract_resource_pv
    return ResourcePropertyValue(property, resource)
  File "/usr/local/lib/python3.10/dist-packages/pronto/utils/[meta.py](http://meta.py/)", line 96, in newfunc
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pronto/[pv.py](http://pv.py/)", line 104, in __init__
    raise ValueError("invalid identifier: {}".format(resource))
ValueError: invalid identifier: https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/ALDH1A1
```

## Possible solutions
I think (2) is likely the only one that will work given how we do things right now.

### 1. Update docker container
I ran it using the `sh run.sh` wrapper. I ran `make update_repo` less than a week ago. But I'm thinking that perhaps the version of OAK in our `odkfull` container is outdated? Probably not good because OAK is probably going to be updated frequently for awhile.

### Add missing `python-install-dependencies` prereq
2. Install Python dependencies before running script: I should have thought of this before, but I just realized after writing this that I probably just need to add my `python-install-dependencies` as a prerequisite. I'm running now and will see if that fixes it.

I added `python-install-dependencies` as a prereq for the `slurp/%.tsv`. Trying it on the right of `|` failed, so I tried putting it on the left, but that did not change anything.

```
pip freeze | grep oaklib; \
python ../scripts/migrate.py \
--ontology-path components/omim.owl \
--sssom-map-path tmp/mondo.sssom.tsv \
--min-id 123000 \
--mondo-terms-path reports/mirror_signature-mondo.tsv \
--outpath slurp/omim.tsv
oaklib==0.1.17  # <---------------------
```

For some reason, OAK is not getting updated, even w/ this prereq:
```
python-install-dependencies:
	python3 -m pip install --upgrade pip
	python3 -m pip install -r $(RELEASEDIR)/requirements-unlocked.txt
```

It shows a virtualenv warning but I don't think this matters in our case:
> ```
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> ```

**Comment by joeflack4** [comment]
Bah, never mind. I'm being clumsy trying to wrap it up for the day, I think. I did fix a bug though; an important one. This will affect all of our scripts that use Python, especially if they use something as frequently updated as OAK.

However, @matentzn do note that one pitfall of this is that this doesn't lock us into specific requirements. I will create a separate issue for this so you don't have to read this one.
